/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fajar
 */
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
public class Laporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan");

        jButton1.setText("Barang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Transaksi Perhari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Transaksi Per Bulan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Transaksi Per Tahun");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Transaction History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try 
           
       {
       Connection conn;
       conn = KoneksiDB.ConnectDB();
       String report = "E:\\report\\report02.jrxml";
       JasperDesign jasperDesign = JRXmlLoader.load(report);
       JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
       JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
       JRViewer test = new JRViewer(jasperPrint);
       JFrame frame = new JFrame("Report");
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       frame.getContentPane().add(test); //new JRViewer(jasperPrint)
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
       frame.pack();
       frame.setVisible(true);    
       frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        
        
       }
       catch (HeadlessException | SQLException | JRException ex) 
       {
           System.out.println(ex);
           System.out.println(System.getProperty("java.endorsed.dirs"));
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try 
           
       {
       Connection conn;
       conn = KoneksiDB.ConnectDB();
       String report = "E:\\report\\report001.jrxml";
       JasperDesign jasperDesign = JRXmlLoader.load(report);
       JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
       JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
       JRViewer test = new JRViewer(jasperPrint);
       JFrame frame = new JFrame("Report");
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       frame.getContentPane().add(test); //new JRViewer(jasperPrint)
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
       frame.pack();
       frame.setVisible(true);    
       frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        
        
       }
       catch (HeadlessException | SQLException | JRException ex) 
       {
           System.out.println(ex);
           System.out.println(System.getProperty("java.endorsed.dirs"));
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   try 
           
       {
       Connection conn;
       conn = KoneksiDB.ConnectDB();
       String report = "E:\\report\\report003.jrxml";
       JasperDesign jasperDesign = JRXmlLoader.load(report);
       JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
       JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
       JRViewer test = new JRViewer(jasperPrint);
       JFrame frame = new JFrame("Report");
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       frame.getContentPane().add(test); //new JRViewer(jasperPrint)
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
       frame.pack();
       frame.setVisible(true);    
       frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        
        
       }
       catch (HeadlessException | SQLException | JRException ex) 
       {
           System.out.println(ex);
           System.out.println(System.getProperty("java.endorsed.dirs"));
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   try 
           
       {
       Connection conn;
       conn = KoneksiDB.ConnectDB();
       String report = "E:\\report\\report002.jrxml";
       JasperDesign jasperDesign = JRXmlLoader.load(report);
       JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
       JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
       JRViewer test = new JRViewer(jasperPrint);
       JFrame frame = new JFrame("Report");
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       frame.getContentPane().add(test); //new JRViewer(jasperPrint)
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
       frame.pack();
       frame.setVisible(true);    
       frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        
        
       }
       catch (HeadlessException | SQLException | JRException ex) 
       {
           System.out.println(ex);
           System.out.println(System.getProperty("java.endorsed.dirs"));
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trans1().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
