


import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fajar
 */
public class Login extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
String user,pass;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         //initComponents();
        try {
        conn = KoneksiDB.ConnectDB();
    } catch (SQLException ex) {
       // Logger.getLogger(Produk.class.getName()).log(Level.SEVERE, null, ex);
    }
        user();
        setIcon();
        
    }
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        //JOptionPane.showMessageDialog(null, "No Image Icon");
    }
    
    private void user(){
    try{
    String sql = "select id_user from user";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    user = rs.getString("id_user");
    
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, "Error Salah");
    }
    }
    private void psw(){
    try{
    String sql = "select password from user";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    pass = rs.getString("password");
    
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, "Error");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jLabel1.setText("User ID");

        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String x,y;
       x = jTextField1.getText();
       y = jPasswordField1.getText();
       //JOptionPane.showMessageDialog(null, x+" "+y);
       try{
       String sql = "select * from pkl.user where id_user='"+x+"' && password='"+y+"'";
       //JOptionPane.showMessageDialog(null, sql);
       //System.out.println(sql);
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
       while(rs.next()){
        String name = rs.getString("ID_USER");
       //String log = name;
        //JOptionPane.showMessageDialog(null, log);
    //String price = rs.getString("harga");
         if (name != null)
       {
           JOptionPane.showMessageDialog(null, "Welcome "+x);
           dispose();
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
       }
         else {
         JOptionPane.showMessageDialog(null, "Login Failed Chek Username and Password");
          
         }
    
    } 
       
       }
       catch (SQLException | HeadlessException Ex){
           JOptionPane.showMessageDialog(null, "Login Failed Chek Username and Password");
       }
           
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
      String x,y;
       x = jTextField1.getText();
       y = jPasswordField1.getText();
       //JOptionPane.showMessageDialog(null, x+" "+y);
       try{
       String sql = "select * from pkl.user where id_user='"+x+"' && password='"+y+"'";
       //JOptionPane.showMessageDialog(null, sql);
       //System.out.println(sql);
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
       while(rs.next()){
        String name = rs.getString("ID_USER");
       //String log = name;
        //JOptionPane.showMessageDialog(null, log);
    //String price = rs.getString("harga");
         if (name != null)
       {
           JOptionPane.showMessageDialog(null, "Welcome "+x);
           dispose();
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
       }
         else {
         JOptionPane.showMessageDialog(null, "Login Failed Chek Username and Password");
          
         }
    
    } 
       
       }
       catch (SQLException | HeadlessException Ex){
           JOptionPane.showMessageDialog(null, "Login Failed Chek Username and Password");
       }
         
    }//GEN-LAST:event_jPasswordField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            try {
                //                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                
                
                // select the Look and Feel
                
                //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            Properties props = new Properties();
            props.put("logoString", "PKL");
            NoireLookAndFeel.setCurrentTheme(props);
            com.jtattoo.plaf.noire.NoireLookAndFeel.setTheme(null, null, "Temp");
            
            //com.jtattoo.plaf.noire.NoireLookAndFeel.setTheme("PKL");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
