
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fajar
 */
public class Orders_Detail extends javax.swing.JInternalFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
String[][] data = null;
int lock = 0;
String[] coloumNames = new String [4];
static JScrollPane scroll;
int stock_brg;
String[][] temp;
 // header is Vector contains table Column
 static Vector headers = new Vector();
 Vector datas = new Vector();
 // Model is used to construct JTable
// static DefaultTableModel model = null;
 // data is Vector contains Data from Excel File
 static Vector dataa = new  Vector();
  static int tableWidth = 0; // set the tableWidth
  static int tableHeight = 0; // set the tableHeight
  int stk;
  int y;
  int gaji;
  int harga,max_harga;
    /**
     * Creates new form Orders_Detail
     */
    public Orders_Detail() {
       initComponents();
         try {
        conn = KoneksiDB.ConnectDB();
    } catch (SQLException ex) {
      //  Logger.getLogger(Produk.class.getName()).log(Level.SEVERE, null, ex);
    }
        //update_table();
       getMax_Nota();
        combobox();
        kombo();
        kombos();
        timeisup();
    }
    
     public void timeisup(){
Calendar cal = new GregorianCalendar();
int date  = cal.get(Calendar.DATE);
int month  = cal.get(Calendar.MONTH);
int year  = cal.get(Calendar.YEAR);
thn.setText(year+"-"+(month+1)+"-"+date);
 }
    private void getMax_Nota()
 {
             try{
    String sql = "select count(*) from orders";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    String price = rs.getString("count(*)");
    int x = Integer.parseInt(price);
    //tm.setText(price);
    id_pen.setText(""+(x+1));
    int b = Integer.parseInt(id_pen.getText());
    jTextField2.setText(""+b);
    //JOptionPane.showMessageDialog(null, price);
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, Ex);
    }
 }

    private void combobox(){
    try{
    String sql = "select id_pegawai from pegawai";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    String name = rs.getString("id_pegawai");
    id_peg.addItem(name);
    //JOptionPane.showMessageDialog(null, price);
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, "Error");
    }
    }
 
 private void kombo(){
  try{
    String sql = "select id_distributor from distributor";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    String name = rs.getString("id_distributor");
    id_dis.addItem(name);
    //String price = rs.getString("harga");
    //tm.setText(price);
    //JOptionPane.showMessageDialog(null, price);
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, Ex);
    }
 }
//    private void update_table(){
//    try {
//            String sql = "select * from transaksi";
//            pst = conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            trans.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kurs = new javax.swing.JTextField();
        th = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id_pen = new javax.swing.JTextField();
        id_peg = new javax.swing.JComboBox();
        id_dis = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employee = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Order");

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Harga");

        kurs.setText("0");

        th.setText("0");

        jLabel2.setText("ID Pegawai");

        jLabel5.setText("Tanggal");

        jLabel3.setText("ID Distributor");

        jLabel6.setText("Kurs");

        jLabel1.setText("ID Order");

        jLabel7.setText("ID Barang");

        jLabel8.setText("Harga");

        jLabel9.setText("ID Order");

        Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Employee);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Jumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(id_peg, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                            .addComponent(id_dis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(th, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kurs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_pen))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_pen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_peg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        masukData();
        insertData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             try {
            try {
                if (lock < 1) {
                    coloumNames = new String[]{"ID Barang", "ID Order", "Harga", "Jumlah"};
                    data = new String[1][4];
                    data[0][0] = (String)jComboBox1.getSelectedItem();
                    data[0][1] = jTextField2.getText();
                    data[0][2] = jTextField1.getText();
                    data[0][3] = jTextField3.getText();
                    //data[0][4] = jTextField4.getText();
//                    data[0][3] = tk.getText();

                    Employee.setModel(new DefaultTableModel(data, coloumNames));
                    lock = lock + 1;

                } else {
                   temp = new String[data.length + 1][data.length + 4];
                    for (int ox = 0; ox < data.length; ox++) {
                        for (int j = 0; j < 4; j++) {
                            temp[ox][j] = data[ox][j];
                        }
                   
                        }
                    temp[data.length][0] = (String)jComboBox1.getSelectedItem();
                    temp[data.length][1] = jTextField2.getText();
                    temp[data.length][2] = jTextField1.getText();
                    temp[data.length][3] = jTextField3.getText();
                    
//                    temp[data.length][3] = tk.getText();

                    data = (String[][]) temp;
                    Employee.setModel(new DefaultTableModel(data, coloumNames));
                    
                    }
//                int j = Integer.parseInt(numb.getText());
//                stk = stk-j;

            } catch (Exception Ex) {
                //JOptionPane.showMessageDialog(null, Ex);
            }
        } catch (Exception Ex) {
        }
        int x1 = Integer.parseInt(jTextField1.getText());
        int x2 = Integer.parseInt(th.getText());
        int x3 = x1+x2;
        th.setText(""+x3);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
                     try {
            int position = Employee.getSelectedRow();
            String[][] temp = new String[data.length - 1][4];
            int totalx = Integer.parseInt(th.getText());
            int i = 0;
            int total2 = Integer.parseInt(data[i][3]);
            int tota3 = totalx-total2;
            th.setText(""+tota3);
            for (i = 0; i < position; i++) {
                temp[i][0] = data[i][0];
                temp[i][1] = data[i][1];
                temp[i][2] = data[i][2];
                temp[i][3] = data[i][3]; 
               
            }
            for (i = position + 1; i < data.length; i++) {
                temp[i - 1][0] = data[i][0];
                temp[i - 1][1] = data[i][1];
                temp[i - 1][2] = data[i][2];
                temp[i - 1][3] = data[i][3];
               
            }
            data = temp;
            Employee.setModel(new DefaultTableModel(data, coloumNames));
            if (data.length < 1) {
                data = null;
                lock = 0;
            }
           // int j = Integer.parseInt(numb.getText());

        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(null, Ex);

            data = null;
        }
        }
        catch (Exception Ex){}
    }//GEN-LAST:event_jButton3ActionPerformed

    void masukData(){
    try {
            //String x = thn.getText()+"-"+bln.getText()+"-"+hari.getText();
            String sql = "INSERT INTO orders (id_order,id_pegawai,id_distributor,harga,tanggal_order,kurs) VALUES(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, id_pen.getText());
            pst.setString(2, (String)id_peg.getSelectedItem());
            pst.setString(3, (String)id_dis.getSelectedItem());
            pst.setString(4, th.getText());
            pst.setString(5, thn.getText());
            pst.setString(6, kurs.getText());
            //              JOptionPane.showMessageDialog(null, id_barang.getText());
            //              JOptionPane.showMessageDialog(null, nama_barang.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
//        update_table();
    }
    
    private void kombos(){
  try{
    String sql = "select id_barang from barang";
     pst = conn.prepareStatement(sql);
     rs=pst.executeQuery();
    
    while(rs.next()){
    String name = rs.getString("id_barang");
    jComboBox1.addItem(name);
    //String price = rs.getString("harga");
    //tm.setText(price);
    //JOptionPane.showMessageDialog(null, price);
    
    }
    }
    catch(SQLException Ex){
    JOptionPane.showMessageDialog(null, Ex);
    }
 }
    
    void insertData()
    {
        
        if (data.length > 0){
        for (int i = 0; i < data.length; i++)
            { 
        try {
            String sql = "INSERT INTO memiliki VALUES ('" + data[i][0] + "','" + data[i][1] + "','"+ data[i][2] +"','"+ data[i][3] +"')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
        } catch (SQLException ex) {
          //  Logger.getLogger(nota.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
            }

    }
        else {
            }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Employee;
    private javax.swing.JComboBox id_dis;
    private javax.swing.JComboBox id_peg;
    private javax.swing.JTextField id_pen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField kurs;
    private javax.swing.JTextField th;
    private javax.swing.JTextField thn;
    // End of variables declaration//GEN-END:variables
}
